### model
model_name_or_path: /mnt/data/hx/Models/Meta-Llama-3-8B-Instruct

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: rpo
template: llama3
cutoff_len: 4096
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/rpo/llama3.1-8b-instruct-rpo
logging_steps: 1
save_steps: 5
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 64
learning_rate:  0.0005
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_offload_config.json
report_to: tensorboard

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 5
flash_attn: fa2